### ISSUE TITLE
项目文件中缺少 requirement.txt

### ISSUE THREAD

**Issue by little1d** [sanbuphy/ChatWithDatawhale#3]
我在复现大佬项目时，发现目录结构中没有依赖文件

**Comment by sanbuphy** [comment]
> 我在复现大佬项目时，发现目录结构中没有依赖文件

hi你好，确实是我漏了，你可以按照这个 项目的 requirement安装后进行 尝试，他们的依赖应该是一样的  https://github.com/SocialAI-tianji/Tianji/blob/main/requirements.txt
